version: "3.8"
services:
  valheim:
    build: .
    container_name: valheim-server
    ports:
      - "2456-2458:2456-2458/udp"
    # volumes:
    #   - /path/to/your/worlds:/root/.config/unity3d/IronGate/Valheim/worlds
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always
